.class public Lorg/telegram/tgnet/tl/TL_stories;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lorg/telegram/tgnet/tl/TL_stories$TL_startLive;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_getAlbumStories;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_getAlbums;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_deleteAlbum;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_reorderAlbums;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_updateAlbum;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_createAlbum;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_togglePinnedToTop;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_getStoryReactionsList;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyReactionsList;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyReaction;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyReactionPublicRepost;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyReactionPublicForward;,
        Lorg/telegram/tgnet/tl/TL_stories$StoryReaction;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stats_getStoryStats;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stats_storyStats;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_prepaidGiveaway;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_prepaidStarsGiveaway;,
        Lorg/telegram/tgnet/tl/TL_stories$PrepaidGiveaway;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_mediaAreaGeoPoint_layer181;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_mediaAreaGeoPoint;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_geoPointAddress;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_inputMediaAreaChannelPost;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_inputMediaAreaVenue;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_mediaAreaWeatherOld;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_mediaAreaWeather;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_mediaAreaWeather2;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_mediaAreaStarGift;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_mediaAreaUrl;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_mediaAreaVenue;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_mediaAreaChannelPost;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_mediaAreaSuggestedReaction;,
        Lorg/telegram/tgnet/tl/TL_stories$MediaArea;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_mediaAreaCoordinates_layer181;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_mediaAreaCoordinates;,
        Lorg/telegram/tgnet/tl/TL_stories$MediaAreaCoordinates;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyItemSkipped;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyItemDeleted;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyItem_layer160;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyItem_layer166;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyItem_layer174;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyItem_layer210;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyItem_layer223;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyItem;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyAlbum;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_albumsNotModified;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_albums;,
        Lorg/telegram/tgnet/tl/TL_stories$Albums;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyFwdHeader;,
        Lorg/telegram/tgnet/tl/TL_stories$StoryFwdHeader;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_publicForwardStory;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyViews;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyViews_layer161;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyViews_layer160;,
        Lorg/telegram/tgnet/tl/TL_stories$StoryViews;,
        Lorg/telegram/tgnet/tl/TL_stories$StoryItem;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_premium_getBoostsList;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_premium_boostsList;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_boost_layer186;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_boost;,
        Lorg/telegram/tgnet/tl/TL_stories$Boost;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_premium_applyBoost;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_premium_getBoostsStatus;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_premium_boostsStatus;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_premium_getMyBoosts;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_premium_myBoosts;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_myBoost;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_getChatsToSend;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_sendReaction;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_activateStealthMode;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storiesStealthMode;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_updateStoriesStealthMode;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_getPeerMaxIDs;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_getAllReadPeerStories;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_report;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_exportStoryLink;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_exportedStoryLink;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_getStoriesViews;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_searchPosts;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_foundStories;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_foundStory;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_getStoriesByID;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_getStoryViewsList;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_incrementStoryViews;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_readStories;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyViewsList_layer167;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyViewsList;,
        Lorg/telegram/tgnet/tl/TL_stories$StoryViewsList;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_updateReadStories;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_getStoriesArchive;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_getPinnedStories;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_updateStory;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_getPeerStories;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_stories;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_togglePeerStoriesHidden;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_getAllStories;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_editStory;,
        Lorg/telegram/tgnet/tl/TL_stories$togglePinned;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_deleteStories;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_sendStory;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_canSendStory;,
        Lorg/telegram/tgnet/tl/TL_stories$canSendStoryCount;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_allStories;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_allStoriesNotModified;,
        Lorg/telegram/tgnet/tl/TL_stories$stories_AllStories;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_peerStories;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_peerStories_layer162;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_peerStories;,
        Lorg/telegram/tgnet/tl/TL_stories$PeerStories;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyViewPublicRepost;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyViewPublicForward;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_storyView;,
        Lorg/telegram/tgnet/tl/TL_stories$StoryView;,
        Lorg/telegram/tgnet/tl/TL_stories$TL_stories_storyViews;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    .line 19
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
