.class public Lorg/telegram/tgnet/tl/TL_update;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lorg/telegram/tgnet/tl/TL_update$TL_updateEphemeralBotCallbackQuery;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateEditEphemeralMessage;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateDeleteEphemeralMessages;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateNewEphemeralMessage;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateWebBrowserException;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateWebBrowserSettings;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateSavedReactionTags;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateRecentReactions;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateEditMessage;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateChatParticipantDelete;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateReadChannelDiscussionOutbox;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateChannelParticipant;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateNotifySettings;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateGeoLiveViewed;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateBotCommands;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateGroupCallConnection;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateChannelMessageViews;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateUserStatus;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateNewEncryptedMessage;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateNewScheduledMessage;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateNewMessage;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateFolderPeers;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateConfig;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updatePrivacy;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateChannelReadMessagesContents;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateChatParticipantAdmin;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateChannelAvailableMessages;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateLangPack;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateUserEmojiStatus;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateTranscribedAudio;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateSavedRingtones;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateServiceNotification;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateUserTyping;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateChannelTooLong;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateGroupCall_layer216;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateGroupCall;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateEncryption;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateLoginToken;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateChatUserTyping;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateChatParticipantAdd;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateFavedStickers;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateWebPage;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateContactsReset;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateSavedGifs;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateDialogFilterOrder;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateReadHistoryInbox;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateRecentStickers;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updatePeerLocated;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updatePinnedDialogs;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateTranscribeAudio;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updatePhoneCallSignalingData;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updatePinnedMessages;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updatePeerBlocked;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateDialogFilter;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updatePhoneCall;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateMessageReactions;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateUserName;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateNewBotConnection;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateNewAuthorization;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateDraftMessage;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateDialogUnreadMark;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateLangPackTooLong;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateTheme;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateNewStickerSet;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateEditChannelMessage;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateDcOptions;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updatePendingJoinRequests;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateRecentEmojiStatuses;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateDialogFilters;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateUser;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateUserPhoto;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateDeleteChannelMessages;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateChannelMessageForwards;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateSentStoryReaction;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateDeleteScheduledMessages;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateChannelWebPage;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateChannel;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateAttachMenuBots;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updatePinnedForumTopic;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updatePinnedForumTopics;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateChatDefaultBannedRights;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateChatParticipants;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateReadMessagesContents;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateReadChannelInbox;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateReadFeaturedEmojiStickers;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateStickerSetsOrder;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateEncryptedMessagesRead;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateWebViewResultSent;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateStarsBalance;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateNewStoryReaction;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateDeleteQuickReplyMessages;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateGroupCallEncryptedMessage;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateDeleteGroupCallMessages;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateGroupCallMessage;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateQuickReplyMessage;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateDeleteQuickReply;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateNewQuickReply;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateQuickReplies;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updatePinnedSavedDialogs;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateChannelViewForumAsMessages;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateStickerSets;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateStoryID;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateChannelUserTyping;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateReadChannelOutbox;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateMessageID;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateUserPhone;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updatePeerSettings;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateDialogPinned;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateAiComposeTones;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateManagedBot;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateChatParticipantRank;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateNewChannelMessage;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateReadHistoryOutbox;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateReadChannelDiscussionInbox;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateEncryptedChatTyping;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateReadFeaturedStickers;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateGroupCallParticipants;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updatePinnedChannelMessages;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateDeleteMessages;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateChat;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateMessagePoll;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updatePeerHistoryTTL;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateMessageExtendedMedia;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateMoveStickerSetToTop;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateMessagePollVote;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateReadMonoForumOutbox;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateReadMonoForumInbox;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateStarGiftCraftFail;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateEmojiGameInfo;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateStarGiftAuctionUserState;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateStarGiftAuctionState;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateJoinChatWebViewDecision;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateMonoForumNoPaidException;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updatePeerWallpaper;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateSavedDialogPinned;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateGroupCallChainBlocks;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateSentPhoneCode;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateBotSubscriptionExpire;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updatePaidReactionPrivacy;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateBotPurchasedPaidMedia;,
        Lorg/telegram/tgnet/tl/TL_update$TL_updateStarsRevenueStatus;
    }
.end annotation


# direct methods
.method private constructor <init>()V
    .locals 0

    .line 12
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
