.class public Lorg/telegram/tgnet/tl/TL_stars;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftAttributeRarityUncommon;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftAttributeRarityLegendary;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftAttributeRarityEpic;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftAttributeRarityRare;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftAttributeRarity;,
        Lorg/telegram/tgnet/tl/TL_stars$StarGiftAttributeRarity;,
        Lorg/telegram/tgnet/tl/TL_stars$craftStarGift;,
        Lorg/telegram/tgnet/tl/TL_stars$getCraftStarGifts;,
        Lorg/telegram/tgnet/tl/TL_stars$getStarGiftUpgradeAttributes;,
        Lorg/telegram/tgnet/tl/TL_stars$starGiftUpgradeAttributes;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftBackground;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_AuctionBidLevel;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_inputStarGiftAuctionSlug;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_inputStarGiftAuction;,
        Lorg/telegram/tgnet/tl/TL_stars$InputStarGiftAuction;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_StarGiftActiveAuctionState;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_StarGiftAuctionAcquiredGift;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_StarGiftAuctionUserState;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftAuctionRoundExtendable;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftAuctionRound;,
        Lorg/telegram/tgnet/tl/TL_stars$StarGiftAuctionRound;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftAuctionStateFinished;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftAuctionStateNotModified;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftAuctionState;,
        Lorg/telegram/tgnet/tl/TL_stars$StarGiftAuctionState;,
        Lorg/telegram/tgnet/tl/TL_stars$checkCanSendGift;,
        Lorg/telegram/tgnet/tl/TL_stars$checkCanSendGiftResultFail;,
        Lorg/telegram/tgnet/tl/TL_stars$checkCanSendGiftResultOk;,
        Lorg/telegram/tgnet/tl/TL_stars$CheckCanSendGiftResult;,
        Lorg/telegram/tgnet/tl/TL_stars$getUniqueStarGiftValueInfo;,
        Lorg/telegram/tgnet/tl/TL_stars$UniqueStarGiftValueInfo;,
        Lorg/telegram/tgnet/tl/TL_stars$getStarGiftCollections;,
        Lorg/telegram/tgnet/tl/TL_stars$deleteStarGiftCollection;,
        Lorg/telegram/tgnet/tl/TL_stars$reorderStarGiftCollections;,
        Lorg/telegram/tgnet/tl/TL_stars$updateStarGiftCollection;,
        Lorg/telegram/tgnet/tl/TL_stars$createStarGiftCollection;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftCollections;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftCollectionsNotModified;,
        Lorg/telegram/tgnet/tl/TL_stars$StarGiftCollections;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftCollection;,
        Lorg/telegram/tgnet/tl/TL_stars$Tl_starsRating;,
        Lorg/telegram/tgnet/tl/TL_stars$getResaleStarGifts;,
        Lorg/telegram/tgnet/tl/TL_stars$resaleStarGifts;,
        Lorg/telegram/tgnet/tl/TL_stars$updateStarGiftPrice;,
        Lorg/telegram/tgnet/tl/TL_stars$toggleStarGiftsPinnedToTop;,
        Lorg/telegram/tgnet/tl/TL_stars$updatePaidMessagesPrice;,
        Lorg/telegram/tgnet/tl/TL_stars$paidReactionPrivacyPeer;,
        Lorg/telegram/tgnet/tl/TL_stars$paidReactionPrivacyAnonymous;,
        Lorg/telegram/tgnet/tl/TL_stars$paidReactionPrivacyDefault;,
        Lorg/telegram/tgnet/tl/TL_stars$PaidReactionPrivacy;,
        Lorg/telegram/tgnet/tl/TL_stars$getStarGiftWithdrawalUrl;,
        Lorg/telegram/tgnet/tl/TL_stars$starGiftWithdrawalUrl;,
        Lorg/telegram/tgnet/tl/TL_stars$toggleChatStarGiftNotifications;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_inputSavedStarGiftChat;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_inputSavedStarGiftSlug;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_inputSavedStarGiftUser;,
        Lorg/telegram/tgnet/tl/TL_stars$InputSavedStarGift;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_payments_savedStarGifts;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_savedStarGift_layer202;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_savedStarGift_layer209;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_savedStarGift_layer211;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_savedStarGift_layer214;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_savedStarGift_layer219;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_savedStarGift_layer221;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_savedStarGift_layer221_2;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_savedStarGift;,
        Lorg/telegram/tgnet/tl/TL_stars$SavedStarGift;,
        Lorg/telegram/tgnet/tl/TL_stars$getUniqueStarGift;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_payments_uniqueStarGift;,
        Lorg/telegram/tgnet/tl/TL_stars$starGiftAttributeOriginalDetails_layer197;,
        Lorg/telegram/tgnet/tl/TL_stars$starGiftAttributeOriginalDetails;,
        Lorg/telegram/tgnet/tl/TL_stars$starGiftAttributeBackdrop_layer202;,
        Lorg/telegram/tgnet/tl/TL_stars$starGiftAttributeBackdrop_layer221;,
        Lorg/telegram/tgnet/tl/TL_stars$starGiftAttributeBackdrop;,
        Lorg/telegram/tgnet/tl/TL_stars$starGiftAttributePattern_layer221;,
        Lorg/telegram/tgnet/tl/TL_stars$starGiftAttributePattern;,
        Lorg/telegram/tgnet/tl/TL_stars$starGiftAttributeModel_layer221;,
        Lorg/telegram/tgnet/tl/TL_stars$starGiftAttributeModel;,
        Lorg/telegram/tgnet/tl/TL_stars$StarGiftAttribute;,
        Lorg/telegram/tgnet/tl/TL_stars$starGiftAttributeIdBackdrop;,
        Lorg/telegram/tgnet/tl/TL_stars$starGiftAttributeIdPattern;,
        Lorg/telegram/tgnet/tl/TL_stars$starGiftAttributeIdModel;,
        Lorg/telegram/tgnet/tl/TL_stars$StarGiftAttributeId;,
        Lorg/telegram/tgnet/tl/TL_stars$starGiftAttributeCounter;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_fulfillStarsSubscription;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_changeStarsSubscription;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_getStarsSubscriptions;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsSubscriptionPricing;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsSubscription_old;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsSubscription_layer193;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsSubscription;,
        Lorg/telegram/tgnet/tl/TL_stars$StarsSubscription;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_payments_sendStarsForm;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_payments_getStarsTransactions;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_payments_getStarsStatus;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_payments_getStarsGiveawayOptions;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_payments_getStarsGiftOptions;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_payments_getStarsTopupOptions;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_payments_starsStatus_layer194;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_payments_starsStatus;,
        Lorg/telegram/tgnet/tl/TL_stars$StarsStatus;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTransaction_layer185;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTransaction_layer186;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTransaction_layer188;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTransaction_layer191;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTransaction_layer194;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTransaction_layer199;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTransaction_layer199_2;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTransaction_layer205;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTransaction;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsAmount;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTonAmount;,
        Lorg/telegram/tgnet/tl/TL_stars$StarsAmount;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTransaction_layer182;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTransaction_layer181;,
        Lorg/telegram/tgnet/tl/TL_stars$StarsTransaction;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTransactionPeerAPI;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTransactionPeerAds;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTransactionPeerUnsupported;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTransactionPeerPremiumBot;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTransactionPeerFragment;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTransactionPeerPlayMarket;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTransactionPeerAppStore;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTransactionPeer;,
        Lorg/telegram/tgnet/tl/TL_stars$StarsTransactionPeer;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsGiveawayOption;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsGiveawayWinnersOption;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsGiftOption;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starsTopupOption;,
        Lorg/telegram/tgnet/tl/TL_stars$getStarGiftUpgradePreview;,
        Lorg/telegram/tgnet/tl/TL_stars$starGiftUpgradePreview;,
        Lorg/telegram/tgnet/tl/TL_stars$StarGiftUpgradePrice;,
        Lorg/telegram/tgnet/tl/TL_stars$transferStarGift;,
        Lorg/telegram/tgnet/tl/TL_stars$upgradeStarGift;,
        Lorg/telegram/tgnet/tl/TL_stars$convertStarGift;,
        Lorg/telegram/tgnet/tl/TL_stars$saveStarGift;,
        Lorg/telegram/tgnet/tl/TL_stars$getSavedStarGift;,
        Lorg/telegram/tgnet/tl/TL_stars$getSavedStarGifts;,
        Lorg/telegram/tgnet/tl/TL_stars$getStarGifts;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftsNotModified;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGifts;,
        Lorg/telegram/tgnet/tl/TL_stars$StarGifts;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGift_layer190;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGift_layer195;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGift_layer202;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGift_layer206;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGift_layer209;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGift_layer212;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGift_layer217;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGift_layer219;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGift;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftUnique_layer196;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftUnique_layer197;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftUnique_layer198;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftUnique_layer202;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftUnique_layer206;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftUnique_layer210;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftUnique_layer211;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftUnique_layer213;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftUnique_layer214;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftUnique_layer215;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftUnique_layer219;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftUnique_layer221;,
        Lorg/telegram/tgnet/tl/TL_stars$TL_starGiftUnique;,
        Lorg/telegram/tgnet/tl/TL_stars$StarGift;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    .line 17
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
